version: '2'
services:
  redis:
    image: redis
    ports:
      - "49300:6379"
  test-books-img:
    build: ./
    command: python /app/run.py
    ports:
      - "49400:5000"
  celery:
    image: celery
    build: ./
    environment:
      - C_FORCE_ROOT=true
      - DATABASE_HOST=redis
      - BROKER_URL=redis://redis:6379
    working_dir: /app
    command: "celery -A test_books:celery worker"
    volumes:
      - .:/app
    depends_on:
      - redis